/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weiyin_letvpiano_ui_tv_bwstaff_DB_MidiJni */

#ifndef _Included_com_weiyin_letvpiano_ui_tv_bwstaff_DB_MidiJni
#define _Included_com_weiyin_letvpiano_ui_tv_bwstaff_DB_MidiJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weiyin_letvpiano_ui_tv_bwstaff_DB_MidiJni
 * Method:    WriteRecordedEvents
 * Signature: ([BLjava/util/ArrayList;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_weiyin_letvpiano_ui_tv_bwstaff_DB_MidiJni_WriteRecordedEvents
        (JNIEnv *, jobject, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
